apiVersion: v2
name: simpaas-stack
description: A Helm chart for complete SimPaaS stack
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: simpaas
  repository: file://../simpaas
  version: ~0
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: ~4
  condition: ingress-nginx.enabled
- name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: ~0
  condition: opentelemetry-collector.enabled
