common:
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext: {}

  env: []

  volumeMounts: []
  volumes: []

  nodeSelector: {}

  affinity: {}

  tolerations: []

smtp:
  enabled: true

  image:
    repository: ixdotai/smtp
    tag: v0.5.2
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext: {}

  env: []
  extraEnv: []

  resoures: {}

  volumeMounts: []
  volumes: []

  nodeSelector: {}

  affinity: {}

  tolerations: []

  port: &smtpPort 25

  livenessProbe: {}
  readinessProbe: {}

swaggerUi:
  enabled: &swaggerUiEnabled true

  replicas: 1

  image:
    repository: swaggerapi/swagger-ui
    tag: v5.17.14
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext: {}

  env: []
  extraEnv: []

  resoures: {}

  volumeMounts: []
  volumes: []

  nodeSelector: {}

  affinity: {}

  tolerations: []

  port: &swaggerUiPort 8080

  livenessProbe: {}
  readinessProbe: {}

  baseUrl: &swaggerUiPath /swagger-ui
  apiUrl: ""

grafana:
  enabled: &grafanaEnabled true

  extraInitContainers:
  - name: openssl
    image: alpine/openssl
    command: [/bin/sh]
    args:
    - -c
    - openssl pkey -pubout -in /opt/simpaas/etc/privkey.pem -out /etc/simpaas/pubkey.pem
    volumeMounts:
    - name: jwt-privkey
      mountPath: /opt/simpaas/etc
      readOnly: true
    - name: jwt-pubkey
      mountPath: /etc/simpaas/
      readOnly: false

  extraVolumeMounts:
  - name: jwt-pubkey
    mountPath: /etc/simpaas
    readOnly: true

  extraVolumes:
  - name: jwt-pubkey
    emptyDir: {}

  extraContainerVolumes:
  - name: jwt-privkey
    secret:
      secretName: &jwtSecretName simpaas-jwt

  service:
    port: &grafanaPort 80

  grafana.ini:
    auth.jwt:
      enabled: true
      header_name: X-SimPaaS-JWT
      username_claim: sub
      email_claim: email
      auto_sign_up: true
      key_file: /etc/simpaas/pubkey.pem

    security:
      cookie_samesite: none

    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true

ingress-nginx:
  enabled: true

  controller:
    ingressClassResource:
      name: &ingressClassName simpaas-nginx

    allowSnippetAnnotations: true

    config:
      http-snippet: |
        map $http_cookie $jwt {
          default "";
          "~*simpaas-jwt=([^;]+)(?:;|$)" $1;
        }

opentelemetry-collector:
  enabled: true

  mode: deployment

  image:
    repository: otel/opentelemetry-collector

  command:
    name: otelcol

simpaas:
  api:
    ingress:
      tls: true

    jwtSecret:
      name: *jwtSecretName

  op:
    smtp:
      port: *smtpPort

  webapp:
    ingress:
      tls: true

  swaggerUi:
    ingress:
      tls: true

  ingress:
    className: *ingressClassName
    annotations:
      acme.cert-manager.io/http01-edit-in-place: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-SimPaaS-JWT $jwt;
    additionalRules:
      grafana:
        enabled: *grafanaEnabled
        path: /grafana
        pathType: ImplementationSpecific
        tls: true
        servicePort: *grafanaPort
        prefixServiceNameByReleaseName: true
      swagger-ui:
        enabled: *swaggerUiEnabled
        path: *swaggerUiPath
        pathType: ImplementationSpecific
        tls: true
        servicePort: *swaggerUiPort
        prefixServiceNameByReleaseName: true
