repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
  - id: check-yaml
    exclude: ^charts
  - id: pretty-format-json
    args: [--autofix]
  - id: trailing-whitespace
    exclude: .rs$
  - id: end-of-file-fixer
    exclude: .rs$
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: ^charts
  - id: pretty-format-toml
    args: [--autofix]
    exclude: ^Cargo.lock
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
  - id: cargo-check
    name: cargo-check
    args: [--tests]
  - id: clippy
    name: clippy
    args: [--tests, --, -D, warnings]
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
  - id: shellcheck
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
  - id: helmlint
- repo: local
  hooks:
  - id: crds
    name: crds
    language: script
    pass_filenames: false
    entry: ./tools/generate-crds.sh
