{{- range $issuer := index .Values "cert-manager" "clusterIssuers" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $issuer.name }}
  labels:
    {{- include "simpaas.labels" $ | nindent 4 }}
    {{- with $issuer.labels }}
    {{- toYaml .| nindent 4 }}
    {{- end }}
spec:
  {{- toYaml $issuer.spec | nindent 2 }}
---
{{- end }}
