{{- if .Values.smtp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simpaas-stack.smtp.name" . }}
  labels:
    {{- include "simpaas-stack.smtp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.smtp.port }}
    targetPort: {{ .Values.smtp.port }}
    protocol: TCP
  selector:
    {{- include "simpaas-stack.smtp.selectorLabels" . | nindent 4 }}
{{- end }}
