{{-  if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "simpaas.serviceAccountName" . }}
  labels:
    {{- include "simpaas.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "simpaas.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "simpaas.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
