apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.simpaas.gleroy.dev
spec:
  group: simpaas.gleroy.dev
  names:
    categories: []
    kind: App
    plural: apps
    shortNames: []
    singular: app
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: SimPaaS application
        properties:
          spec:
            properties:
              namespace:
                description: Namespace.
                type: string
              owner:
                description: Owner of the app.
                type: string
              services:
                description: List of app services.
                items:
                  properties:
                    expose:
                      default: []
                      description: List of ports to expose.
                      items:
                        properties:
                          ingress:
                            description: If specified, an ingress will be created to expose the service. If not specified, the serive is only exposes locally.
                            nullable: true
                            properties:
                              domain:
                                description: Domain part of URL.
                                minLength: 3
                                type: string
                              tls:
                                default: false
                                description: True if TLS is enabled.
                                type: boolean
                            required:
                            - domain
                            type: object
                          port:
                            description: The port to expose.
                            format: uint16
                            minimum: 0.0
                            type: integer
                          protocol:
                            default: TCP
                            description: The protocol.
                            minLength: 1
                            type: string
                        required:
                        - port
                        type: object
                      type: array
                    image:
                      description: Image repository.
                      minLength: 1
                      type: string
                    name:
                      description: Service name.
                      minLength: 1
                      type: string
                    replicas:
                      default: 1
                      description: Replicas.
                      format: uint16
                      minimum: 0.0
                      type: integer
                    tag:
                      default: latest
                      description: Image tag.
                      minLength: 1
                      type: string
                    values:
                      additionalProperties: true
                      default: {}
                      description: Helm chart values.
                      type: object
                  required:
                  - image
                  - name
                  type: object
                type: array
              values:
                additionalProperties: true
                default: {}
                description: Helm chart values.
                type: object
            required:
            - namespace
            - owner
            - services
            type: object
        required:
        - spec
        title: App
        type: object
    served: true
    storage: true
    subresources: {}
