apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.simpaas.gleroy.dev
spec:
  group: simpaas.gleroy.dev
  names:
    categories: []
    kind: Application
    plural: applications
    shortNames:
    - app
    singular: application
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: An application
        properties:
          spec:
            properties:
              containers:
                default: []
                items:
                  properties:
                    databases:
                      default: []
                      items:
                        properties:
                          mapping:
                            default:
                              host: DATABASE_HOST
                              name: DATABASE_NAME
                              password: DATABASE_PASSWORD
                              port: DATABASE_PORT
                              user: DATABASE_USER
                            properties:
                              host:
                                default: DATABASE_HOST
                                type: string
                              name:
                                default: DATABASE_NAME
                                type: string
                              password:
                                default: DATABASE_PASSWORD
                                type: string
                              port:
                                default: DATABASE_PORT
                                type: string
                              user:
                                default: DATABASE_USER
                                type: string
                            type: object
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      type: array
                    exposes:
                      default: []
                      items:
                        properties:
                          ingress:
                            nullable: true
                            properties:
                              domain:
                                type: string
                              path:
                                default: /
                                type: string
                            required:
                            - domain
                            type: object
                          port:
                            format: uint16
                            minimum: 0.0
                            type: integer
                        required:
                        - port
                        type: object
                      type: array
                    image:
                      type: string
                    name:
                      type: string
                    tag:
                      type: string
                  required:
                  - image
                  - name
                  - tag
                  type: object
                type: array
              monitorDelay:
                default: 30
                format: uint32
                minimum: 0.0
                type: integer
              tlsDomains:
                default: []
                items:
                  type: string
                type: array
            type: object
          status:
            enum:
            - Healthy
            - Degraded
            - Deploying
            - DeploymentFailed
            - UndeploymentFailed
            - Unknown
            nullable: true
            type: string
        required:
        - spec
        title: Application
        type: object
    served: true
    storage: true
    subresources:
      status: {}
