apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.simpaas.gleroy.dev
spec:
  group: simpaas.gleroy.dev
  names:
    categories: []
    kind: Database
    plural: databases
    shortNames:
    - db
    singular: database
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: A database
        properties:
          spec:
            properties:
              database:
                type: string
                x-kubernetes-validations:
                - rule: self == oldSelf
              instance:
                type: string
                x-kubernetes-validations:
                - rule: self == oldSelf
              user:
                type: string
                x-kubernetes-validations:
                - rule: self == oldSelf
            required:
            - database
            - instance
            - user
            type: object
          status:
            enum:
            - Created
            - Creating
            - CreationFailed
            - DropFailed
            - Dropping
            - Unknown
            nullable: true
            type: string
        required:
        - spec
        title: Database
        type: object
    served: true
    storage: true
    subresources:
      status: {}
