apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: roles.simpaas.gleroy.dev
spec:
  group: simpaas.gleroy.dev
  names:
    categories: []
    kind: Role
    plural: roles
    shortNames: []
    singular: role
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: SimPaaS user role
        properties:
          spec:
            properties:
              permissions:
                default: []
                description: Role permissions.
                items:
                  oneOf:
                  - required:
                    - createApp
                  - required:
                    - deleteApp
                  - required:
                    - inviteUsers
                  - required:
                    - updateApp
                  properties:
                    createApp:
                      description: Allow role to create app.
                      type: object
                    deleteApp:
                      description: Allow role to delete app.
                      properties:
                        name:
                          default: .*
                          description: Pattern that matches app name.
                          type: string
                      type: object
                    inviteUsers:
                      description: Allow role to invite users.
                      type: object
                    updateApp:
                      description: Allow roel to update app.
                      properties:
                        name:
                          default: .*
                          description: Pattern that matches app name.
                          type: string
                      type: object
                  type: object
                type: array
            type: object
        required:
        - spec
        title: Role
        type: object
    served: true
    storage: true
    subresources: {}
