apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceinstances.simpaas.gleroy.dev
spec:
  group: simpaas.gleroy.dev
  names:
    categories: []
    kind: ServiceInstance
    plural: serviceinstances
    shortNames:
    - svcinst
    singular: serviceinstance
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: An instance of a service
        properties:
          spec:
            properties:
              service:
                type: string
                x-kubernetes-validations:
                - rule: self == oldSelf
              values:
                additionalProperties: true
                default: {}
                type: object
            required:
            - service
            type: object
          status:
            enum:
            - Healthy
            - Degraded
            - Deploying
            - DeploymentFailed
            - UndeploymentFailed
            - Unknown
            nullable: true
            type: string
        required:
        - spec
        title: ServiceInstance
        type: object
    served: true
    storage: true
    subresources:
      status: {}
