apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.simpaas.gleroy.dev
spec:
  group: simpaas.gleroy.dev
  names:
    categories: []
    kind: Service
    plural: services
    shortNames:
    - svc
    singular: service
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: A service
        properties:
          spec:
            properties:
              chart:
                type: string
              monitorDelay:
                default: 30
                format: uint32
                minimum: 0.0
                type: integer
              values:
                type: string
              version:
                nullable: true
                type: string
            required:
            - chart
            - values
            type: object
        required:
        - spec
        title: Service
        type: object
    served: true
    storage: true
    subresources: {}
