apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.simpaas.gleroy.dev
spec:
  group: simpaas.gleroy.dev
  names:
    categories: []
    kind: Service
    plural: services
    shortNames:
    - svc
    singular: service
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: A service
        properties:
          spec:
            properties:
              chart:
                type: string
              consumes:
                default:
                  database: null
                properties:
                  database:
                    nullable: true
                    properties:
                      creationJob:
                        type: string
                      dropJob:
                        type: string
                      host:
                        type: string
                      passwordSecret:
                        default:
                          key: password
                          name: db-creds-{{ name }}
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                      port:
                        format: uint32
                        minimum: 0.0
                        type: integer
                    required:
                    - creationJob
                    - dropJob
                    - host
                    - port
                    type: object
                type: object
              monitorDelay:
                default: 30
                format: uint32
                minimum: 0.0
                type: integer
              values:
                type: string
              version:
                nullable: true
                type: string
            required:
            - chart
            - values
            type: object
        required:
        - spec
        title: Service
        type: object
    served: true
    storage: true
    subresources: {}
