{{- if .Values.secret.create }}
{{- $secretName := include "simpaas-postgresql.secretName" . }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $postgresPassword := "" }}
{{- $repmgrPassword := "" }}
{{- $pgpoolAdminPassword := "" }}
{{- if $secret }}
{{- $postgresPassword = index $secret.data .Values.secret.key.postgresPassword }}
{{- $repmgrPassword = index $secret.data .Values.secret.key.repmgrPassword }}
{{- $pgpoolAdminPassword = index $secret.data .Values.secret.key.pgpoolAdminPassword }}
{{- else }}
{{- $postgresPassword = randAlphaNum 12 | b64enc }}
{{- $repmgrPassword = randAlphaNum 12 | b64enc }}
{{- $pgpoolAdminPassword = randAlphaNum 12 | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simpaas-postgresql.secretName" . }}
  labels:
    {{- include "simpaas-postgresql.labels" . | nindent 4 }}
data:
  {{ .Values.secret.key.postgresPassword }}: {{ $postgresPassword }}
  {{ .Values.secret.key.repmgrPassword }}: {{ $repmgrPassword }}
  {{ .Values.secret.key.pgpoolAdminPassword }}: {{ $pgpoolAdminPassword }}
{{- end }}
