apiVersion: simpaas.gleroy.dev/v1
kind: Application
metadata:
  name: nginx
  namespace: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    tag: latest
    databases:
    - name: test
    exposes:
    - port: 80
      ingress:
        domain: &nginxDomain nginx.k8s.orb.local
  tlsDomains:
  - *nginxDomain
