common:
  image:
    tag: ~
    pullPolicy: IfNotPresent
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext: {}

  env: []

  volumeMounts: []
  volumes: []

  nodeSelector: {}

  affinity: {}

  tolerations: []

  otel:
    enabled: false
    collectorUrl: ~

  logFilter: ~

serviceAccount:
  create: true
  name: ~
  automount: true

rbac:
  create: true
  rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

api:
  replicas: 1

  image:
    repository: gleroy/simpaas-api
    tag: ~
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  securityContext:
    readOnlyRootFilesystem: true
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

  env: []

  resoures: {}

  volumeMounts: []
  volumes: []

  nodeSelector: {}

  affinity: {}

  tolerations: []

  port: 8080

  livenessProbe:
    httpGet:
      path: /api/_health
      port: http
  readinessProbe:
    httpGet:
      path: /api/_health
      port: http

  jwtSecret:
    create: true
    name: ~
    key: secret

  logFilter: ~

  ingress:
    enabled: true
    domain: ~
    fqdn: ~
    tls: false
    path: /api
    pathType: ImplementationSpecific

  roleAdmin:
    create: true
    name: admin
    permissions:
    - createApp: {}
    - deleteApp: {}
    - inviteUsers: {}
    - readApp: {}
    - updateApp: {}

  admin:
    create: true
    name: admin
    secret:
      name: ~
      key: password

op:
  replicas: 1

  image:
    repository: gleroy/simpaas-op
    tag: ~
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  securityContext:
    readOnlyRootFilesystem: true
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

  env: []

  resoures: {}

  volumeMounts: []
  volumes: []

  nodeSelector: {}

  affinity: {}

  tolerations: []

  livenessProbe: {}
  readinessProbe: {}

  chartValues: {}

  logFilter: ~

  smtp:
    host: ~
    port: 25
    tls: false
    implicitTls: false
    authEnabled: false
    credentialsSecret:
      name: ~
      userKey: user
      passwordKey: password

  webappUrl: ~

webapp:
  port: 3000

  ingress:
    enabled: true
    domain: ""
    fqdn: ~
    tls: false
    path: /
    pathType: ImplementationSpecific

ingress:
  create: true
  className: ~
  domain: ~
  tlsSecretName: ~
  annotations: {}

smtp:
  enabled: true

  image:
    repository: ixdotai/smtp
    tag: v0.5.2
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext: {}

  env: []

  resoures: {}

  volumeMounts: []
  volumes: []

  nodeSelector: {}

  affinity: {}

  tolerations: []

  port: 25

  livenessProbe: {}
  readinessProbe: {}

swaggerUi:
  enabled: true

  replicas: 1

  image:
    repository: swaggerapi/swagger-ui
    tag: v5.17.14
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext: {}

  env: []

  resoures: {}

  volumeMounts: []
  volumes: []

  nodeSelector: {}

  affinity: {}

  tolerations: []

  port: 8080

  livenessProbe: {}
  readinessProbe: {}

  ingress:
    enabled: true
    className: ~
    domain: ~
    fqdn: ~
    tls: false
    path: /swagger-ui
    pathType: ImplementationSpecific
