{{- if .Values.api.admin.create }}
{{- $password := randAlphaNum 12 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-%s" .Release.Name .Values.api.admin.name) .Values.api.admin.secret.name }}
  labels:
    {{- include "simpaas.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
data:
  {{ .Values.api.admin.secret.key }}: {{ $password | b64enc  }}
---
apiVersion: simpaas.gleroy.dev/v1
kind: User
metadata:
  name: {{ .Values.api.admin.name }}
  labels:
    {{- include "simpaas.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
spec:
  password: {{ trimPrefix (printf "%s:" .Values.api.admin.name) (htpasswd .Values.api.admin.name $password) }}
  {{- if .Values.api.roleAdmin.create }}
  roles: [{{ .Values.api.roleAdmin.name }}]
  {{- end }}
{{- end }}
