{{- if .Values.api.admin.create }}
{{- $secretName := default (printf "%s-%s" .Release.Name .Values.api.admin.name) .Values.api.admin.secret.name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName  -}}
{{- $password := "" -}}
{{- if $secret -}}
{{- $password = (index $secret.data .Values.api.admin.secret.key) | b64dec -}}
{{- else -}}
{{- $password = randAlphaNum 12 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "simpaas.labels" . | nindent 4 }}
data:
  {{ .Values.api.admin.secret.key }}: {{ $password | b64enc  }}
---
apiVersion: simpaas.gleroy.dev/v1
kind: User
metadata:
  name: {{ .Values.api.admin.name }}
  labels:
    {{- include "simpaas.labels" . | nindent 4 }}
spec:
  password: {{ trimPrefix (printf "%s:" .Values.api.admin.name) (htpasswd .Values.api.admin.name $password) }}
  {{- if .Values.api.roleAdmin.create }}
  roles: [{{ .Values.api.roleAdmin.name }}]
  {{- end }}
{{- end }}
