common:
  image:
    tag: latest
    pullPolicy: Always

  logFilter: simpaas=debug,warn

op:
  replicas: 0

ingress:
  domain: simpaas.k8s.orb.local

smtp:
  enabled: true

  env:
  - name: GMAIL_USER
    valueFrom:
      secretKeyRef:
        name: simpaas-gmail
        key: user
  - name: GMAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: simpaas-gmail
        key: password
