{{- if .Values.swaggerUi.enabled }}
{{- $podAnnotations := merge .Values.common.podAnnotations .Values.swaggerUi.podAnnotations -}}
{{- $podLabels := merge .Values.common.podLabels .Values.swaggerUi.podLabels -}}
{{- $imagePullSecrets := concat .Values.common.imagePullSecrets .Values.swaggerUi.imagePullSecrets -}}
{{- $podSecurityContext := merge .Values.common.podSecurityContext .Values.swaggerUi.podSecurityContext -}}
{{- $securityContext := merge .Values.common.securityContext .Values.swaggerUi.securityContext -}}
{{- $env := concat .Values.common.env .Values.swaggerUi.env .Values.swaggerUi.extraEnv -}}
{{- $volumeMounts := concat .Values.common.volumeMounts .Values.swaggerUi.volumeMounts -}}
{{- $volumes := concat .Values.common.volumes .Values.swaggerUi.volumes -}}
{{- $nodeSelector := merge .Values.common.nodeSelector .Values.swaggerUi.nodeSelector -}}
{{- $affinity := merge .Values.common.affinity .Values.swaggerUi.affinity -}}
{{- $tolerations := concat .Values.common.tolerations .Values.swaggerUi.tolerations -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simpaas-stack.swaggerUi.name" . }}
  labels:
    {{- include "simpaas-stack.swaggerUi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.swaggerUi.replicas }}
  selector:
    matchLabels:
      {{- include "simpaas-stack.swaggerUi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "simpaas-stack.swaggerUi.labels" . | nindent 8 }}
        {{- with $podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $podSecurityContext | nindent 8 }}
      containers:
      - name: swagger-ui
        securityContext:
          {{- toYaml $securityContext | nindent 12 }}
        image: {{ printf "%s:%s" .Values.swaggerUi.image.repository .Values.swaggerUi.image.tag }}
        imagePullPolicy: {{ default .Values.common.imagePullPolicy .Values.swaggerUi.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.swaggerUi.port }}
          protocol: TCP
        {{- with .Values.swaggerUi.livenessProbe }}
        livenessProbe:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.swaggerUi.readinessProbe }}
        readinessProbe:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $env }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.swaggerUi.resources | nindent 10 }}
        {{- with $volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $volumes }}
      volumes:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
