apiVersion: v1
kind: Service
metadata:
  name: {{ include "simpaas.webapp.name" . }}
  labels:
    {{- include "simpaas.webapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.webapp.port }}
    targetPort: {{ .Values.webapp.port }}
    protocol: TCP
  selector:
    {{- include "simpaas.webapp.selectorLabels" . | nindent 4 }}
