{{- if .Values.secret.create }}
{{- $postgresPassword := "" -}}
{{- $repmgrPassword := "" -}}
{{- $secretName := include "simpaas-postgresql.secret.name" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $pgpoolAdminPassword := include "utils.generateSecretIfDoesNotExist" (dict "secret" $secret "key" .Values.secret.pgpoolAdminPasswordKey) }}
{{- $postgresPassword := include "utils.generateSecretIfDoesNotExist" (dict "secret" $secret "key" .Values.secret.postgresPasswordKey) }}
{{- $repmgrPassword := include "utils.generateSecretIfDoesNotExist" (dict "secret" $secret "key" .Values.secret.repmgrPasswordKey) }}
apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "simpaas-postgresql.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml | nindent 4 }}
    {{- end }}
  name: {{ $secretName }}
data:
  {{ .Values.secret.pgpoolAdminPasswordKey }}: {{ $pgpoolAdminPassword }}
  {{ .Values.secret.postgresPasswordKey }}: {{ $postgresPassword }}
  {{ .Values.secret.repmgrPasswordKey }}: {{ $repmgrPassword }}
type: Opaque
{{- end }}
