apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "simpaas-postgresql.labels" . | nindent 4 }}
  name: {{ include "simpaas-postgresql.postgresql.service.headlessName" . }}
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
  selector:
    {{- include "simpaas-postgresql.postgresql.podLabels" . | nindent 6 }}
---
{{ if .Values.postgresql.service.create }}
{{- $annotations := merge .Values.postgresql.service.annotations .Values.common.service.annotations -}}
{{- $externalTrafficPolicy := default .Values.common.service.externalTrafficPolicy .Values.postgresql.service.externalTrafficPolicy -}}
{{- $internalTrafficPolicy := default .Values.common.service.internalTrafficPolicy .Values.postgresql.service.internalTrafficPolicy -}}
{{- $ipFamilies := concat .Values.common.service.ipFamilies .Values.postgresql.service.ipFamilies -}}
{{- $ipFamilyPolicy := default .Values.common.service.ipFamilyPolicy .Values.postgresql.service.ipFamilyPolicy -}}
{{- $labels := merge .Values.postgresql.service.labels .Values.common.service.labels -}}
{{- $loadBalancerClass := default .Values.common.service.loadBalancerClass .Values.postgresql.service.loadBalancerClass -}}
{{- $loadBalancerSourceRanges := concat .Values.common.service.loadBalancerSourceRanges .Values.postgresql.service.loadBalancerSourceRanges -}}
{{- $sessionAffinity := default .Values.common.service.sessionAffinity .Values.postgresql.service.sessionAffinity -}}
{{- $sessionAffinityConfig := merge .Values.postgresql.service.sessionAffinityConfig .Values.common.service.sessionAffinityConfig -}}
{{- $trafficDistribution := default .Values.common.service.trafficDistribution .Values.postgresql.service.trafficDistribution -}}
apiVersion: v1
kind: Service
metadata:
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "simpaas-postgresql.labels" . | nindent 4 }}
    {{- with $labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "simpaas-postgresql.postgresql.name" . }}
spec:
  {{- if not (eq nil .Values.postgresql.service.allocateLoadBalancerNodePorts) }}
  allocateLoadBalancerNodePorts: {{ .Values.postgresql.service.allocateLoadBalancerNodePorts }}
  {{- end }}
  {{- if .Values.postgresql.service.clusterIp }}
  clusterIP: {{ .Values.postgresql.service.clusterIp }}
  {{- end }}
  {{- with .Values.postgresql.service.clusterIPs }}
  clusterIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.postgresql.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.postgresql.service.externalName }}
  externalName: {{ .Values.postgresql.service.externalName }}
  {{- end }}
  {{- if $externalTrafficPolicy }}
  externalTrafficPolicy: {{ $externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.postgresql.service.healthCheckNodePort }}
  healthCheckNodePort: {{ .Values.postgresql.service.healthCheckNodePort }}
  {{- end }}
  {{- if $internalTrafficPolicy }}
  internalTrafficPolicy: {{ $internalTrafficPolicy }}
  {{- end }}
  {{- with $ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $ipFamilyPolicy }}
  ipFamilyPolicy: {{ $ipFamilyPolicy }}
  {{- end }}
  {{- if $loadBalancerClass }}
  loadBalancerClass: {{ $loadBalancerClass }}
  {{- end }}
  {{- if .Values.postgresql.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.postgresql.service.loadBalancerIP }}
  {{- end }}
  {{- with $loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: postgresql
      {{- if .Values.postgresql.service.nodePort }}
      nodePort: {{ .Values.postgresql.service.nodePort }}
      {{- end }}
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
  {{- if not (eq nil .Values.postgresql.service.publishNotReadyAddresses) }}
  publishNotReadyAddresses: {{ .Values.postgresql.service.publishNotReadyAddresses }}
  {{- end }}
  selector:
    {{- include "simpaas-postgresql.postgresql.podLabels" . | nindent 6 }}
  {{- if $sessionAffinity }}
  sessionAffinity: {{ $sessionAffinity }}
  {{- end }}
  {{- with $sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $trafficDistribution }}
  trafficDistribution: {{ $trafficDistribution }}
  {{- end }}
  type: {{ .Values.postgresql.service.type }}
{{- end }}
