{{- if .Values.api.jwtSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simpaas.api.jwtSecretName" . }}
  labels:
    {{- include "simpaas.api.labels" . | nindent 8 }}
type: Opaque
data:
  {{ .Values.api.jwtSecret.key }}: {{ randAlphaNum 12 | b64enc }}
{{- end }}
