{{- if .Values.api.jwtSecret.create }}
{{- $secretName := include "simpaas.api.jwtSecretName" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $privkey := "" -}}
{{- if $secret -}}
{{- $privkey = index $secret.data .Values.api.jwtSecret.key -}}
{{- else -}}
{{- $privkey = genPrivateKey "rsa" | b64enc -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "simpaas.api.labels" . | nindent 8 }}
type: Opaque
data:
  {{ .Values.api.jwtSecret.key }}: {{ $privkey }}
{{- end }}
