apiVersion: v1
kind: Service
metadata:
  name: {{ include "simpaas.api.name" . }}
  labels:
    {{- include "simpaas.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
    protocol: TCP
  selector:
    {{- include "simpaas.api.selectorLabels" . | nindent 4 }}
