apiVersion: simpaas.gleroy.dev/v1
kind: Service
metadata:
  name: postgresql
  namespace: simpaas
spec:
  chart:
    name: charts/simpaas-postgresql
    values: |
      labels:
        simpaas.gleroy.dev/service: {{ service }}
        simpaas.gleroy.dev/service-instance: {{ name }}
  consumes:
    database:
      host: '{{ instance.name }}-pgpool.{{ instance.namespace }}.svc.{{ domain }}'
      port: 5432
      creationJob: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: database-creation-{{ name }}
          namespace: {{ instance.namespace }}
          labels:
            simpaas.gleroy.dev/database: {{ name }}
            simpaas.gleroy.dev/job-kind: creation
        spec:
          template:
            metadata:
              labels:
                simpaas.gleroy.dev/database: {{ name }}
                simpaas.gleroy.dev/job-kind: creation
            spec:
              restartPolicy: OnFailure
              containers:
              - name: creation
                image: bitnami/postgresql
                command:
                - sh
                - -xec
                args:
                - |
                  if psql -h $HOST -p $PORT -U $PG_USER -tc "SELECT 1 FROM pg_roles WHERE rolname = '$DB_USER'" | grep -q 1; then
                    echo "user $DB_USER already created"
                  else
                    echo "creating user $DB_USER"
                    psql -h $HOST -p $PORT -U $PG_USER -c "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_USER_PASSWORD'"
                    echo "user $DB_USER created"
                  fi
                  if psql -h $HOST -p $PORT -U $PG_USER -tc "SELECT 1 FROM pg_dataabse WHERE datname = '$NAME'" | grep -q 1; then
                    echo "database $NAME already created"
                  else
                    echo "creating database $NAME"
                    psql -h $HOST -p $PORT -U $PG_USER -c "CREATE DATABASE $NAME OWNER $DB_USER"
                    echo "database $NAME created"
                  fi
                env:
                - name: DB_USER
                  value: {{ user }}
                - name: DB_USER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ passwordSecret.name }}
                      key: {{ passwordSecret.key }}
                - name: HOST
                  value: {{ host }}
                - name: NAME
                  value: {{ database }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ instance.name }}-creds
                      key: postgres-password
                - name: PG_USER
                  value: postgres
                - name: PORT
                  value: "{{ port }}"
      dropJob: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: database-drop-{{ name }}
          namespace: {{ instance.namespace }}
          labels:
            simpaas.gleroy.dev/database: {{ name }}
            simpaas.gleroy.dev/job-kind: deletion
        spec:
          template:
            metadata:
              labels:
                simpaas.gleroy.dev/database: {{ name }}
                simpaas.gleroy.dev/job-kind: deletion
            spec:
              restartPolicy: OnFailure
              containers:
              - name: drop
                image: bitnami/postgresql
                command:
                - sh
                - -xec
                args:
                - |
                  psql -h $HOST -p $PORT -U $PG_USER -c "DROP DATABASE IF EXISTS $NAME (FORCE)"
                  psql -h $HOST -p $PORT -U $PG_USER -c "DROP ROLE IF EXISTS $DB_USER"
                env:
                - name: DB_USER
                  value: {{ user }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ instance.name }}-creds
                      key: postgres-password
                - name: PG_USER
                  value: postgres
                - name: HOST
                  value: {{ host }}
                - name: NAME
                  value: {{ database }}
                - name: PORT
                  value: "{{ port }}"
