apiVersion: v2
name: simpaas-local
description: A Helm chart for local SimPaaS install
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: simpaas
  repository: file://../simpaas
  version: ~0
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: ~4
  condition: ingress-nginx.enabled
