serviceAccount:
  create: true
  name: ""
  automount: true

ingress:
  className: simpaas-nginx
  annotations: {}

common:
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext: {}

  env: []

  volumeMounts: []
  volumes: []

  nodeSelector: {}

  affinity: {}

  tolerations: []

services: []
