[dependencies]
anyhow = "1"
clap = {version = "4", features = ["derive", "env"]}
simpaas-core = {path = "../core"}
tokio = {version = "1", features = ["full"]}

[package]
description = "SimPaaS operator"
name = "simpaas-operator"
edition.workspace = true
version.workspace = true
