{{- if .Values.smtp.enabled }}
{{- $podAnnotations := merge .Values.common.podAnnotations .Values.smtp.podAnnotations -}}
{{- $podLabels := merge .Values.common.podLabels .Values.smtp.podLabels -}}
{{- $imagePullSecrets := concat .Values.common.imagePullSecrets .Values.smtp.imagePullSecrets -}}
{{- $podSecurityContext := merge .Values.common.podSecurityContext .Values.smtp.podSecurityContext -}}
{{- $securityContext := merge .Values.common.securityContext .Values.smtp.securityContext -}}
{{- $env := concat .Values.common.env .Values.smtp.env -}}
{{- $volumeMounts := concat .Values.common.volumeMounts .Values.smtp.volumeMounts -}}
{{- $volumes := concat .Values.common.volumes .Values.smtp.volumes -}}
{{- $nodeSelector := merge .Values.common.nodeSelector .Values.smtp.nodeSelector -}}
{{- $affinity := merge .Values.common.affinity .Values.smtp.affinity -}}
{{- $tolerations := concat .Values.common.tolerations .Values.smtp.tolerations -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simpaas.smtp.name" . }}
  labels:
    {{- include "simpaas.smtp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.smtp.replicas }}
  selector:
    matchLabels:
      {{- include "simpaas.smtp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "simpaas.smtp.labels" . | nindent 8 }}
        {{- with $podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "simpaas.serviceAccountName" . }}
      securityContext:
        {{- toYaml $podSecurityContext | nindent 8 }}
      containers:
      - name: smtp
        securityContext:
          {{- toYaml $securityContext | nindent 12 }}
        image: {{ printf "%s:%s" .Values.smtp.image.repository .Values.smtp.image.tag }}
        imagePullPolicy: {{ default .Values.common.image.pullPolicy .Values.smtp.image.pullPolicy }}
        ports:
        - name: smtp
          containerPort: {{ .Values.smtp.port }}
          protocol: TCP
        {{- with .Values.smtp.livenessProbe }}
        livenessProbe:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.smtp.readinessProbe }}
        readinessProbe:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: PORT
          value: {{ .Values.smtp.port | quote }}
        {{- with .Values.smtp.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.smtp.resources | nindent 10 }}
        {{- with $volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $volumes }}
      volumes:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
